version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    networks:
      - banknator
    environment:
      MYSQL_ROOT_PASSWORD: Gudmord92!
      MYSQL_DATABASE: banknator
      MYSQL_USER: banknatordb
      MYSQL_PASSWORD: Gudmord92!
    ports:
      - "3322:3306"
    volumes:
      - db:/lib/mysql
  app:
    depends_on:
      - mysql
    build: ./
    restart: on-failure
    networks:
      - banknator
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://banknator-mysql-1:3306/banknator?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: banknatordb
      SPRING_DATASOURCE_PASSWORD: Gudmord92!

    stdin_open: true
    tty: true
networks:
  banknator:

volumes:
  db:


